### ISSUE TITLE
Import file into R

### ISSUE THREAD

**Issue by jmarkgraf** [mberneaud/PairAssignment3#1]
Hi Malte,

For the import of the file: I had quite some issues with it and eventually solved it by saving the file as a txt (UTF16) and imported it as such to R. Furthermore, I had to define the column length of the document. It looked like the following:
read.table("....txt", sep = "\t", quote = "", header = TRUE, fileEncoding = "UTF-16", fill = TRUE)[ ,1:X]

**Comment by mberneaud** [comment]
Thanks, I'll give it a try in a second.

**Comment by jmarkgraf** [comment]
I tried to knit the document but apparently there is sth wrong with the data import. Do you want me to have a look at your code or would you like to correct it yourself?

**Comment by mberneaud** [comment]
Okay, that's easily fixed. As I couldn't use the Dropbox folder which you used as a working directory, which is a Git repo in my home folder ( ~/Git/PairAssignment3) in my case, I created a folder named "data" in the root directory of the repo and copied the files from our shared Dropbox into that.

The .gitignore file in the repo's root directory is configured so that it prevents your data from being included in the remote repo. 

 I'll make a note about this in the introduction of the RMarkdown so Christopher knows also.

**Comment by jmarkgraf** [comment]
Great, thanks!
